export const KEY_NOT_DEFINED_IN_SCHEMA = 'ROOT/ROOT_KEY_NOT_DEFINED_IN_SCHEMA';

export const IS_REQUIRED = 'IS_REQUIRED/IS_REQUIRED';

export const TYPE_MUST_BE_STRING = 'TYPE/TYPE_MUST_BE_STRING';
export const TYPE_MUST_BE_NUMBER = 'TYPE/TYPE_MUST_BE_NUMBER';
export const TYPE_MUST_BE_BOOLEAN = 'TYPE/TYPE_MUST_BE_BOOLEAN';
export const TYPE_MUST_BE_BUFFER = 'TYPE/TYPE_MUST_BE_BUFFER';
export const TYPE_MUST_BE_DATE = 'TYPE/TYPE_MUST_BE_DATE';
export const TYPE_MUST_BE_ARRAY = 'TYPE/TYPE_MUST_BE_ARRAY';
export const TYPE_MUST_BE_ONE_OF = 'TYPE/TYPE_MUST_BE_ONE_OF';

export const MATCH_DOES_NOT_MATCH_PATTERN = 'MATCH/MATCH_DOES_NOT_MATCH_PATTERN';

export const IN_DOES_NOT_MATCH_VALUES = 'IN/IN_DOES_NOT_MATCH_VALUES';

export const MIN_MUST_BE_GREATER_THAN = 'MIN/MIN_MUST_BE_GREATER_THAN';
export const MIN_MUST_BE_GREATER_THAN_CHAR = 'MIN/MIN_MUST_BE_GREATER_THAN_CHAR';

export const MAX_MUST_BE_LESS_THAN = 'MAX/MAX_MUST_BE_LESS_THAN';
export const MAX_MUST_BE_LESS_THAN_CHAR = 'MAX/MAX_MUST_BE_LESS_THAN_CHAR';

export const EQUALS_TO_MUST_BE_EQUAL = 'EQUALS_TO/EQUALS_TO_MUST_BE_EQUAL';
